"""Deterministically render GitHub workflow bytes from a compiled CI graph."""

from __future__ import annotations

import copy
import difflib
import re
import shlex
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .ci_github_actions import action_pin
from .ci_graph_contracts import CompiledCIGraph, validate_ci_graph
from .ci_graph_yaml import render_yaml
from .governance_install.transaction import apply_transaction


GENERATED_HEADER = "# Generated by BCF; edit governance/ci-graph.yml or a registered extension."
SELECTED_PYTHON = "${{ env.pythonLocation }}/bin/python"
RUNNER_TEMP_PREFIX = "${{ runner.temp }}/"
RUN_ATTEMPT_SUFFIX = "-${{ github.run_id }}-${{ github.run_attempt }}"
RUNNER_TEMP_ROOT = re.compile(
    re.escape(RUNNER_TEMP_PREFIX) + r"(?P<root>[A-Za-z0-9_.-]+)"
)


@dataclass(frozen=True)
class CIGraphRenderResult:
    status: str
    changed_paths: tuple[str, ...]


def _scope_runner_temp_value(value: Any) -> Any:
    """Project every runner-temp root into the current run and attempt."""

    if isinstance(value, str):
        return RUNNER_TEMP_ROOT.sub(
            lambda match: RUNNER_TEMP_PREFIX
            + match.group("root")
            + RUN_ATTEMPT_SUFFIX,
            value,
        )
    if isinstance(value, dict):
        return {key: _scope_runner_temp_value(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_scope_runner_temp_value(item) for item in value]
    return value


def _events(events: list[dict[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for event in events:
        kind = event["type"]
        if kind == "schedule":
            result[kind] = [{"cron": value} for value in event.get("cron", [])]
            continue
        config: dict[str, Any] = {}
        for key in ("branches", "workflows", "types", "inputs"):
            if key in event:
                config[key] = event[key]
        result[kind] = config
    return result


def _condition(compiled: CompiledCIGraph, value: str) -> str | None:
    if value == "success":
        return None
    expression = (
        value + "()"
        if value in {"always", "failure", "cancelled"}
        else compiled.graph["conditions"][value]
    )
    return "${{ " + expression + " }}"


def _command_step(
    compiled: CompiledCIGraph, command_id: str, *, name: str
) -> dict[str, Any]:
    command = compiled.commands[command_id]
    argv: list[str] = []
    for value in command["argv"]:
        if value == "{python}":
            argv.append('"$BCF_PYTHON"')
        elif value == "{controller}":
            argv.append(compiled.trusted_controller)
        elif value == "{ephemeral_controller}":
            argv.append('"$RUNNER_TEMP"/bcf-controller/bin/bcf')
        elif value.startswith("{env:") and value.endswith("}"):
            env_name = value[5:-1]
            if not env_name.replace("_", "A").isalnum() or env_name.upper() != env_name:
                raise AssertionError(f"invalid governed environment placeholder {value}")
            argv.append(f'"${env_name}"')
        else:
            argv.append(
                '"' + value.replace('"', '\\"') + '"'
                if "${{" in value and "}}" in value
                else shlex.quote(value)
            )
    environment = {
        "BCF_PYTHON": SELECTED_PYTHON,
        **command["environment"],
    }
    for required in command["required_environment"]:
        environment[required] = "${{ env." + required + " }}"
    return {
        "name": name,
        "shell": "bash",
        "working-directory": command["cwd"],
        "env": environment,
        "run": (
            "set -euo pipefail\n"
            + "".join(f'test -n "${name}"\n' for name in command["required_environment"])
            + " ".join(argv)
        ),
    }


def _component_steps(
    compiled: CompiledCIGraph, component_ids: list[str]
) -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = []
    for component_id in component_ids:
        component = compiled.graph["step_components"][component_id]
        if component["kind"] == "directory_setup":
            paths = " ".join(shlex.quote(value) for value in component["paths"])
            steps.append(
                {
                    "name": component["name"],
                    "shell": "bash",
                    "run": f"set -euo pipefail\nmkdir -p -- {paths}",
                }
            )
            continue
        if component["kind"] == "controller_install":
            if "wheel_sha256" in component:
                expected_digest = repr(component["wheel_sha256"])
                digest_loader = ""
            else:
                expected_digest = "expected"
                digest_loader = (
                    f"authority=pathlib.Path({component['wheel_sha256_file']!r})\n"
                    "assert authority.is_file() and not authority.is_symlink()\n"
                    "payload=json.loads(authority.read_text())\n"
                    f"keys={component['wheel_sha256_key'].split('.')!r}\n"
                    "expected=payload\n"
                    "for key in keys:\n"
                    " assert isinstance(expected,dict) and key in expected\n"
                    " expected=expected[key]\n"
                    "assert isinstance(expected,str) and re.fullmatch(r'[a-f0-9]{64}',expected)\n"
                )
            script = (
                "import hashlib,json,pathlib,re,subprocess,sys,venv\n"
                f"source=pathlib.Path({component['artifact_dir']!r})\n"
                f"target=pathlib.Path({component['install_root']!r})\n"
                + digest_loader
                + "inventory=source/'SHA256SUMS'\n"
                "assert inventory.is_file() and not inventory.is_symlink()\n"
                "declared={}\n"
                "for line in inventory.read_text().splitlines():\n"
                " digest,separator,name=line.partition('  ')\n"
                " assert separator and len(digest)==64 and name and name not in declared\n"
                " declared[name]=digest\n"
                "actual={path.name:path for path in source.iterdir() if path.name!='SHA256SUMS'}\n"
                "assert set(actual)==set(declared)\n"
                "assert all(path.is_file() and not path.is_symlink() and hashlib.sha256(path.read_bytes()).hexdigest()==declared[name] for name,path in actual.items())\n"
                "wheels=sorted(source.glob('bcf_governance-*.whl'))\n"
                "assert len(wheels)==1 and not wheels[0].is_symlink()\n"
                f"assert hashlib.sha256(wheels[0].read_bytes()).hexdigest()=={expected_digest}\n"
                "venv.EnvBuilder(with_pip=True,clear=True).create(target)\n"
                "subprocess.run([str(target/'bin/python'),'-m','pip','install','--no-index','--find-links',str(source),str(wheels[0])],check=True)\n"
                "subprocess.run([str(target/'bin/bcf'),'ci-github','--help'],check=True)\n"
            )
            step = {
                "name": component["name"],
                "shell": "bash",
                "run": "set -euo pipefail\npython -I -c " + shlex.quote(script),
            }
            steps.append(step)
            continue
        if component["kind"] == "action":
            step: dict[str, Any] = {
                "name": component["name"],
                "uses": action_pin(component["action"]),
            }
            if component["with"]:
                step["with"] = copy.deepcopy(component["with"])
        else:
            step = _command_step(
                compiled, component["command"], name=component["name"]
            )
            if component["environment"]:
                step["env"].update(component["environment"])
        if component["id"] is not None:
            step["id"] = component["id"]
        if component["condition"] is not None:
            step["if"] = _condition(compiled, component["condition"])
        if component["kind"] == "action" and component["environment"]:
            step["env"] = component["environment"]
        steps.append(step)
    return steps


def _artifact_producer(
    compiled: CompiledCIGraph, artifact: str
) -> tuple[dict[str, Any], dict[str, Any]]:
    for workflow in compiled.workflows:
        for job in workflow["jobs"]:
            if artifact in job["produces"]:
                return workflow, job
    raise AssertionError(f"artifact {artifact} has no producer")


def _artifact_runtime_path(
    compiled: CompiledCIGraph, job: dict[str, Any], artifact: str
) -> str:
    if job["trust"] == "trusted" and job["checkout"] is False:
        return f"${{{{ runner.temp }}}}/bcf-{artifact}"
    return str(compiled.graph["artifacts"][artifact]["path"])


def _download_steps(
    compiled: CompiledCIGraph, workflow: dict[str, Any], job: dict[str, Any]
) -> list[dict[str, Any]]:
    steps: list[dict[str, Any]] = []
    for artifact in job["consumes"]:
        producer_workflow, _ = _artifact_producer(compiled, artifact)
        cross_workflow = producer_workflow["id"] != workflow["id"]
        run_id = (
            "${{ github.event.workflow_run.id }}"
            if cross_workflow
            else "${{ github.run_id }}"
        )
        run_attempt = (
            "${{ github.event.workflow_run.run_attempt }}"
            if cross_workflow
            else "${{ github.run_attempt }}"
        )
        artifact_contract = compiled.graph["artifacts"][artifact]
        with_values: dict[str, Any] = {
            "name": f"bcf-{artifact}-{run_id}-{run_attempt}",
            "path": _artifact_runtime_path(compiled, job, artifact),
        }
        if cross_workflow:
            with_values.update(
                {
                    "github-token": "${{ github.token }}",
                    "repository": "${{ github.repository }}",
                    "run-id": run_id,
                }
            )
        step: dict[str, Any] = {
            "name": f"Download exact {artifact} evidence",
            "uses": action_pin("download-artifact"),
            "with": with_values,
        }
        if (
            job["executor"]["kind"] == "authority"
            and job["executor"]["operation"] == "publish"
        ):
            step["continue-on-error"] = True
        steps.append(step)
    return steps


def _upload_steps(
    compiled: CompiledCIGraph, job: dict[str, Any]
) -> list[dict[str, Any]]:
    return [
        {
            "name": f"Upload exact {artifact} evidence",
            "if": "${{ always() }}",
            "uses": action_pin("upload-artifact"),
            "with": {
                "name": f"bcf-{artifact}-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}",
                "path": _artifact_runtime_path(compiled, job, artifact),
                "if-no-files-found": "error",
                "retention-days": compiled.graph["artifacts"][artifact]["retention_days"],
            },
        }
        for artifact in job["produces"]
    ]


def _executor_steps(compiled: CompiledCIGraph, job: dict[str, Any]) -> list[dict[str, Any]]:
    executor = job["executor"]
    if executor["kind"] in {"command", "truth"}:
        return [_command_step(compiled, executor["command"], name=job["display_name"])]
    if executor["kind"] == "gate_group":
        gates = " ".join(shlex.quote(value) for value in executor["gates"])
        return [
            {
                "name": "Capture each governed gate once",
                "shell": "bash",
                "env": {
                    "BCF_PYTHON": SELECTED_PYTHON,
                    "BCF_GATES": gates,
                },
                "run": (
                    "set -euo pipefail\n"
                    "mapfile -t manifests < <(find .artifacts/bcf/sessions -type f -name evidence-session.json -print)\n"
                    "test \"${#manifests[@]}\" -eq 1\n"
                    "session=\"${manifests[0]}\"\n"
                    "session_dir=\"${session%/evidence-session.json}\"\n"
                    "for gate in $BCF_GATES; do\n"
                    "  \"$BCF_PYTHON\" scripts/governance_evidence.py --repo-root . run "
                    "--gate \"$gate\" --output \"$session_dir/$gate\" "
                    "--python \"$BCF_PYTHON\" --session-manifest \"$session\"\n"
                    "done"
                ),
            }
        ]
    if executor["kind"] == "authority":
        operation = executor["operation"]
        produced_path = (
            _artifact_runtime_path(compiled, job, job["produces"][0])
            if job["produces"]
            else ""
        )
        consumed_path = (
            _artifact_runtime_path(compiled, job, job["consumes"][0])
            if job["consumes"]
            else ""
        )
        arguments = {
            "admit": (
                'exact-main admit --repository "$GITHUB_REPOSITORY" --sha "$GITHUB_SHA" '
                '--target-url "https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"'
            ),
            "finalize": (
                'exact-main finalize --repository "$GITHUB_REPOSITORY" '
                f'--output "{produced_path}"'
            ),
            "publish": (
                'exact-main publish --repository "$GITHUB_REPOSITORY" '
                f'--bundle "{consumed_path}" '
                '--target-url "https://github.com/$GITHUB_REPOSITORY/actions/runs/${{ github.event.workflow_run.id }}" '
                '--collector-run-id "${{ github.event.workflow_run.id }}" '
                '--collector-run-attempt "${{ github.event.workflow_run.run_attempt }}"'
            ),
            "authorize-release": "release authorize --repository \"$GITHUB_REPOSITORY\"",
            "collect-release": "release collect --repository \"$GITHUB_REPOSITORY\"",
            "publish-release": "release publish --repository \"$GITHUB_REPOSITORY\"",
        }[operation]
        return [
            {
                "name": job["display_name"],
                "shell": "bash",
                "env": {"GITHUB_TOKEN": "${{ github.token }}"},
                "run": (
                    "set -euo pipefail\n"
                    f"{compiled.trusted_controller_check}\n"
                    f"{compiled.trusted_controller} ci-github {arguments}"
                ),
            }
        ]
    if executor["kind"] in {"component_sequence", "gate_shard", "terminal_truth"}:
        return _component_steps(compiled, executor["components"])
    raise AssertionError(f"unsupported executor {executor['kind']}")


def _job(
    compiled: CompiledCIGraph, workflow: dict[str, Any], job: dict[str, Any]
) -> dict[str, Any]:
    executor = job["executor"]
    result: dict[str, Any] = {"name": job["display_name"]}
    if job["needs"]:
        result["needs"] = job["needs"]
    condition = _condition(compiled, job["condition"])
    if (
        job["controller_requirement"] == "current"
        and not compiled.trusted_controller_current
    ):
        condition = "${{ false }}"
    if condition is not None:
        result["if"] = condition
    if job["permissions"]:
        result["permissions"] = copy.deepcopy(job["permissions"])
    if job["outputs"]:
        result["outputs"] = copy.deepcopy(job["outputs"])
    if executor["kind"] == "reusable_workflow":
        result["uses"] = "./" + executor["path"]
        if executor["inputs"]:
            result["with"] = executor["inputs"]
        return result
    resource = compiled.graph["resource_classes"][job["resource_class"]]
    result["runs-on"] = copy.deepcopy(resource["runner"])
    result["timeout-minutes"] = job["timeout_minutes"]
    if "strategy" in job:
        strategy = job["strategy"]
        result["strategy"] = {
            "fail-fast": strategy["fail_fast"],
            **(
                {"max-parallel": strategy["max_parallel"]}
                if "max_parallel" in strategy
                else {}
            ),
            "matrix": copy.deepcopy(strategy["matrix"]),
        }
    elif "matrix" in job:
        result["strategy"] = {
            "fail-fast": True,
            "matrix": copy.deepcopy(job["matrix"]),
        }
    if job["environment"]:
        result["env"] = copy.deepcopy(job["environment"])
    steps: list[dict[str, Any]] = []
    if job["checkout"]:
        steps.append(
            {
                "name": "Check out the exact candidate commit",
                "uses": action_pin("checkout"),
                "with": {"persist-credentials": False},
            }
        )
    if "python" in job["components"]:
        steps.append(
            {
                "name": "Provision the declared Python runtime",
                "uses": action_pin("setup-python"),
                "with": {"python-version": resource["python_version"]},
            }
        )
    if "governance-dependencies" in job["components"]:
        steps.append(
            {
                "name": "Install the declared governance environment",
                "shell": "bash",
                "run": (
                    "set -euo pipefail\n"
                    '"$pythonLocation/bin/python" -m pip install '
                    "-r requirements-governance.txt"
                ),
            }
        )
    explicit_components = executor["kind"] in {
        "component_sequence",
        "gate_shard",
        "terminal_truth",
    }
    if not explicit_components:
        steps.extend(_download_steps(compiled, workflow, job))
    if "restore-private-modes" in job["components"]:
        steps.append(
            {
                "name": "Restore private evidence-session modes",
                "shell": "bash",
                "run": (
                    "set -euo pipefail\n"
                    "find .artifacts/bcf -type f -name evidence-session.json "
                    "-execdir chmod 700 . \\; -exec chmod 400 {} +"
                ),
            }
        )
    steps.extend(_executor_steps(compiled, job))
    if not explicit_components:
        steps.extend(_upload_steps(compiled, job))
    if "scoped-cleanup" in job["components"]:
        steps.append(
            {
                "name": "Clean only repository-owned CI resources",
                "if": "${{ always() }}",
                "shell": "bash",
                "run": "set -euo pipefail\nbcf ci-cleanup --repo-root .",
            }
        )
    result["steps"] = steps
    if job["trust"] == "trusted" and job["checkout"] is False:
        result = _scope_runner_temp_value(result)
    return result


def _workflow(compiled: CompiledCIGraph, workflow: dict[str, Any]) -> bytes:
    workflow_environment = copy.deepcopy(workflow["environment"])
    if any(event["type"] == "pull_request" for event in workflow["events"]):
        workflow_environment = {
            "BCF_ENFORCE_PR_CHANGELOG": "${{ github.event_name == 'pull_request' }}",
            "BCF_PR_BASE_SHA": "${{ github.event.pull_request.base.sha }}",
            **workflow_environment,
        }
    payload: dict[str, Any] = {
        "name": workflow["display_name"],
        "on": _events(workflow["events"]),
        "permissions": copy.deepcopy(workflow["permissions"]),
    }
    if workflow_environment:
        payload["env"] = workflow_environment
    if "concurrency" in workflow:
        payload["concurrency"] = {
            "group": workflow["concurrency"]["group"],
            "cancel-in-progress": workflow["concurrency"]["cancel_in_progress"],
        }
    payload["jobs"] = {
        job["id"]: _job(compiled, workflow, job) for job in workflow["jobs"]
    }
    provenance = (
        f"{GENERATED_HEADER}\n"
        f"# graph-sha256: {compiled.graph_sha256}\n"
        f"# extension-sha256: {','.join(digest for _, digest in compiled.extension_sha256) or 'none'}\n"
        f"# input-sha256: {','.join(digest for _, digest in compiled.input_sha256) or 'none'}\n"
    )
    return provenance.encode("utf-8") + render_yaml(payload)


def render_ci_graph(repo_root: Path) -> dict[str, bytes]:
    compiled = validate_ci_graph(repo_root)
    return {
        workflow["path"]: _workflow(compiled, workflow)
        for workflow in sorted(compiled.workflows, key=lambda item: item["path"])
    }


def _managed_generated_paths(repo_root: Path, desired: dict[str, bytes]) -> tuple[str, ...]:
    paths = set(desired)
    workflow_root = repo_root / ".github/workflows"
    if workflow_root.is_dir() and not workflow_root.is_symlink():
        for path in workflow_root.glob("*.y*ml"):
            if path.is_file() and not path.is_symlink() and path.read_text(
                encoding="utf-8"
            ).startswith(GENERATED_HEADER):
                paths.add(path.relative_to(repo_root).as_posix())
    return tuple(sorted(paths))


def _changed(repo_root: Path, desired: dict[str, bytes]) -> tuple[str, ...]:
    managed = _managed_generated_paths(repo_root, desired)
    changed: list[str] = []
    for path in managed:
        current = repo_root / path
        if path not in desired or not current.is_file() or current.read_bytes() != desired[path]:
            changed.append(path)
    return tuple(changed)


def check_ci_graph(repo_root: Path) -> CIGraphRenderResult:
    repo_root = repo_root.resolve()
    desired = render_ci_graph(repo_root)
    changed = tuple(sorted(set(_changed(repo_root, desired))))
    return CIGraphRenderResult("clean" if not changed else "drift", changed)


def apply_ci_graph(repo_root: Path) -> CIGraphRenderResult:
    repo_root = repo_root.resolve()
    desired = render_ci_graph(repo_root)
    managed = _managed_generated_paths(repo_root, desired)
    before = check_ci_graph(repo_root).changed_paths

    def mutate(shadow: Path) -> None:
        for relative in managed:
            path = shadow / relative
            if relative not in desired:
                if path.exists():
                    path.unlink()
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(desired[relative])

    apply_transaction(repo_root, managed_paths=managed, mutate_shadow=mutate)
    return CIGraphRenderResult("clean" if not before else "applied", before)


def diff_ci_graph(repo_root: Path) -> str:
    repo_root = repo_root.resolve()
    desired = render_ci_graph(repo_root)
    chunks: list[str] = []
    for relative in _managed_generated_paths(repo_root, desired):
        current = (repo_root / relative).read_text(encoding="utf-8").splitlines(True) if (repo_root / relative).is_file() else []
        target = desired.get(relative, b"").decode("utf-8").splitlines(True)
        chunks.extend(
            difflib.unified_diff(current, target, fromfile=f"a/{relative}", tofile=f"b/{relative}")
        )
    return "".join(chunks)
